# Generated by Django 3.2.5 on 2021-07-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='car_price',
            field=models.IntegerField(),
        ),
    ]
